#!/usr/bin/env bash
#$ -cwd
#$ -N templateCase_Allrun
#$ -pe orte 16
#$ -o log.$JOB_ID.out
#$ -e log.$JOB_ID.err
#$ -m n
echo "Utilizing: $NSLOTS cores"

source /nfs/prg/OpenFOAM/OpenFOAM-dev/platforms/stargate.env

#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy aerofoil surface from resources directory
cp $FOAM_TUTORIALS/resources/geometry/NACA0012.obj.gz constant/geometry/

runApplication blockMesh
runApplication transformPoints "scale=(1 0 1)"
runApplication extrudeMesh
runApplication decomposePar

runParallel foamRun

rm -rf processor*
#------------------------------------------------------------------------------

# End of convertToBatch auto-conversion
